name: 💡 Feature request
description: Share an idea or suggest a new feature for this project
title: "[IDEA]: "
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following.
      options:
        - label: I checked the [existing issues](https://github.com/foenichs/Bonfire/issues) for duplicate suggestions
          required: true
        - label: I have ensured that my idea isn't already a thing in the latest version of the plugin
          required: true
  - type: textarea
    attributes:
      label: Describe your idea
      description: A detailed description of your idea and why it should be implemented. You can also include screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots to your suggestion here, if you want.
    validations:
      required: false